### ISSUE TITLE
Informationen über den Interrail Pass

### ISSUE THREAD

**Issue by luxn** [luxn/geoinf#10]

**Comment by li2215** [comment]
[interrail_railway_map_of_europe_2017.pdf](https://github.com/luxn/geoinf/files/970515/interrail_railway_map_of_europe_2017.pdf)
PDF zu den Zugstrecken

**Comment by li2215** [comment]
[Interrail Pass.pdf](https://github.com/luxn/geoinf/files/970526/Interrail.Pass.pdf)
Preisklassen und Länder

**Comment by luxn** [comment]
Nächstes mal nicht die Issue direkt immer ❌ , gibt eine 📫 mehr als sonst 

Wie werden die Information in der 📱 Präsentiert? Mockups?
