### ISSUE TITLE
Icons erstellen oder aus Material Design

### ISSUE THREAD

**Issue by luxn** [luxn/geoinf#16]

**Comment by li2215** [comment]
Eigentlich gibt es doch nur ein Icon oder ? das "Info" Icon

**Comment by luxn** [comment]
Trip Icon, Bahn Icon, Wetter Icon, Unterkunft Icon, Teilen Icon, Twitter Icon, Facebook Icon, Tour Icon, etc etc.

**Comment by luxn** [comment]
Icon Font https://material.io/icons/
