### ISSUE TITLE
Datenquellen / API's heraussuchen, Analysieren

### ISSUE THREAD

**Issue by luxn** [luxn/geoinf#3]
z.B. Airbnb, Yahoo Weather, Google Places / OSM etc.

**Comment by luxn** [comment]
Wettter:
https://openweathermap.org/
Bietet bis zu 60 Abfragen pro Minute kostenfrei an. Wetterdaten allerdings 2-3 Stunden verspätet

Bsp London als Dokumentation
https://openweathermap.org/current


Bsp JSON Response für Cairns, Australien, Temperatur ist in Kelvin
```
{
   "coord":{
      "lon":145.77,
      "lat":-16.92
   },
   "weather":[
      {
         "id":803,
         "main":"Clouds",
         "description":"broken clouds",
         "icon":"04n"
      }
   ],
   "base":"cmc stations",
   "main":{
      "temp":293.25,
      "pressure":1019,
      "humidity":83,
      "temp_min":289.82,
      "temp_max":295.37
   },
   "wind":{
      "speed":5.1,
      "deg":150
   },
   "clouds":{
      "all":75
   },
   "rain":{
      "3h":3
   },
   "dt":1435658272,
   "sys":{
      "type":1,
      "id":8166,
      "message":0.0166,
      "country":"AU",
      "sunrise":1435610796,
      "sunset":1435650870
   },
   "id":2172797,
   "name":"Cairns",
   "cod":200
}
```

Alternative evtl. mit API-Key ist Yahoo Weather 
https://developer.yahoo.com/weather/

**Comment by luxn** [comment]
GTFS
https://developers.google.com/transit/gtfs/

![Image of GTFS Feed](https://developers.google.com/transit/images/gtfs-feed-diagram.png)

Ältere Daten hiervon z.B. in lokale realtionale SQLite Datenbank in Android, wenn keine Realtimedaten als Feed verfügbar sind.

https://github.com/fredlockheed/db-fv-gtfs
https://transit.land/
https://code.google.com/archive/p/googletransitdatafeed/wikis/PublicFeeds.wiki
https://github.com/patrickbr/db-api-to-gtfs
https://data.gov.ie/dataset/gtfs-irish-rail
https://www.europeandataportal.eu/data/en/dataset?tags=gtfs

**Comment by luxn** [comment]
http://airbnbapi.org/

https://developers.google.com/maps/android/?hl=de

**Comment by lengab** [comment]
Infos zu Interrail
http://de.interrail.eu/passes/how-use-your-interrail-pass

Geodaten Bahnstrecken
http://www.openrailwaymap.org/ Web-Karte
http://wiki.openstreetmap.org/wiki/OpenRailwayMap

Google Places
https://developers.google.com/places/?hl=de

Alternativen zu GTFS jeweils auf Nationale Bahnnetze beschränkt
https://hello.irail.be/api/1-0/ Bahn API für Belgien 
http://www.transportapi.com/ für GB

**Comment by lengab** [comment]
Wir verwenden nicht: 
Daten aus der mcloud - keine europäische Datengrundlage, stark auf Firmen/Orte eingeschränkt
